# **Pytorch Basics**
---

Make sure that you have installed pytorch using the following command.

```python 
torch.__version__
```

## Imports

In [1]:
import torch
import numpy as np

# Tensor Basics
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type. Check out the link for more details about **torch.tensor** and **Data Types**:

https://pytorch.org/docs/stable/tensors.html

## Converting Numpy Arrays to Pytorch Tensors

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [3]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)
print(x)
print(type(x))
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
torch.int64
torch.LongTensor


In [4]:
# Floating point datatypes
arr2 = np.arange(0.,9.).reshape(3,3)
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.dtype)
print(x2.type())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
torch.float64
torch.DoubleTensor


## Copy and Share Memory(from Numpy array to Pytorch tensor)
Im the commands below, the Pytorch tensor and Numpy array **share** the memory, and changes to one affects another:
```python
torch.from_numpy()
torch.as_tensor()
```

But, the function below makes a **Copy**:
```python
torch.tensor()
```

In [5]:
# Use torch.from_numpy()
arr = np.arange(0,5)
tensor_ = torch.from_numpy(arr)
print('Old value: ', tensor_)

# Change one elemtent of Numpy array
arr[2]=77
print('New value: ', tensor_)

Old value:  tensor([0, 1, 2, 3, 4])
New value:  tensor([ 0,  1, 77,  3,  4])


In [7]:
# Use torch.tensor()
arr = np.arange(0,3)
tensor_ = torch.tensor(arr)
print('Old value: ', tensor_)

# Change one elemtent of Numpy array
arr[2]=77
print('New value: ', tensor_)

Old value:  tensor([0, 1, 2])
New value:  tensor([0, 1, 2])


## Class Constructors
The factory function below, determines the dtype from the input data:
```python
torch.tensor(data)
```

The class constuctor below is an **alias** for `torch.FloatTensor(data)`:
```python
torch.Tensor(data)
```

In [8]:
data = np.array([1,2,3])
a = torch.Tensor(data)  # Equivalent to a = torch.FloatTensor(data)
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


In [9]:
b = torch.tensor(data)
print(b)
print(b.type())

tensor([1, 2, 3])
torch.LongTensor


In [10]:
c = torch.tensor(data, dtype=torch.int32)
print(c)
print(c.type())

tensor([1, 2, 3], dtype=torch.int32)
torch.IntTensor


## Create Pytorch Tensor Directly
The command below, creates a tensor without initializing its values. It allocates a block of memory based on the tensor's size and returns the values that happen to be in that memory block, which is similar to how `numpy.empty()` works:
```python
torch.empty()
```

In [11]:
x = torch.empty(2, 3)
print(x)

tensor([[-4.5267e+08,  4.5860e-41, -4.5272e+08],
        [ 4.5860e-41, -4.5260e+08,  4.5860e-41]])


## Zeros and Ones


In [14]:
x = torch.zeros(2, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [13]:
y = torch.ones(2, 3, dtype=torch.float16)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
