# **Pytorch Basics**
---

Make sure that you have installed pytorch using the following command.

```python 
torch.__version__
```

## Imports

In [1]:
import torch
import numpy as np

# Tensor Basics
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type. Check out the link for more details about **torch.tensor** and **Data Types**:

https://pytorch.org/docs/stable/tensors.html

## Converting Numpy Arrays to Pytorch Tensors

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [3]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)
print(x)
print(type(x))
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
torch.int64
torch.LongTensor


In [4]:
# Floating point datatypes
arr2 = np.arange(0.,9.).reshape(3,3)
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.dtype)
print(x2.type())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
torch.float64
torch.DoubleTensor


## Copy and Share Memory(from Numpy array to Pytorch tensor)
Im the commands below, the Pytorch tensor and Numpy array **share** the memory, and changes to one affects another:
```python
torch.from_numpy()
torch.as_tensor()
```

But, the function below makes a **Copy**:
```python
torch.tensor()
```

In [5]:
# Use torch.from_numpy()
arr = np.arange(0,5)
tensor_ = torch.from_numpy(arr)
print('Old value: ', tensor_)

# Change one elemtent of Numpy array
arr[2]=77
print('New value: ', tensor_)

Old value:  tensor([0, 1, 2, 3, 4])
New value:  tensor([ 0,  1, 77,  3,  4])


In [6]:
# Use torch.tensor()
arr = np.arange(0,3)
tensor_ = torch.tensor(arr)
print('Old value: ', tensor_)

# Change one elemtent of Numpy array
arr[2]=77
print('New value: ', tensor_)

Old value:  tensor([0, 1, 2])
New value:  tensor([0, 1, 2])


## Class Constructors
The factory function below, determines the dtype from the input data:
```python
torch.tensor(data)
```

The class constuctor below is an **alias** for `torch.FloatTensor(data)`:
```python
torch.Tensor(data)
```

In [7]:
data = np.array([1,2,3])
a = torch.Tensor(data)  # Equivalent to a = torch.FloatTensor(data)
print(a)
print(a.type())

tensor([1., 2., 3.])
torch.FloatTensor


In [8]:
b = torch.tensor(data)
print(b)
print(b.type())

tensor([1, 2, 3])
torch.LongTensor


In [9]:
c = torch.tensor(data, dtype=torch.int32)
print(c)
print(c.type())

tensor([1, 2, 3], dtype=torch.int32)
torch.IntTensor


## Create Pytorch Tensor Directly

### Tensor Initialization
The command below, creates a tensor without initializing its values. It allocates a block of memory based on the tensor's size and returns the values that happen to be in that memory block, which is similar to how `numpy.empty()` works:
```python
torch.empty()
```

In [10]:
x = torch.empty(2, 3)
print(x)

tensor([[ 1.5456e-42,  0.0000e+00, -2.6438e+13],
        [ 3.0641e-41,  3.2230e-44,  0.0000e+00]])


### Zeros and Ones


In [11]:
x = torch.zeros(2, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [12]:
y = torch.ones(2, 3, dtype=torch.float16)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)


## Tensor from Ranges
The `step`in the `arange` is **exclusive**, but in `linspace` is **inclusive**.
```python
torch.arange(start,end,step)
```

```python
torch.linspace(start,end,steps)
```

In [13]:
x = torch.arange(0,7,2).reshape(2,2)
x

tensor([[0, 2],
        [4, 6]])

In [14]:
x = torch.linspace(0,9,10).reshape(2,5)
x

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

## Tensor from Data

In [15]:
# torch.tensor() choose the dtype based on the input data.
x = torch.tensor([1, 2, 3])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3])
torch.int64
torch.LongTensor


In [16]:
# Set the type by the tensor method
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


In [17]:
# Set the dtype parameter
x = torch.tensor([8,1,-3], dtype=torch.int32)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  1, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


## Change dtype of Created Tensor
instead of using the command below that raise a warning of improper use of tensor cloning:
```python
x = torch.tensor(x, dtype=torch.int)
```
use the method below:
```python
x.type()
```

In [18]:
print('Old:', x.dtype)

x = x.type(torch.int64)
print('New:', x.dtype)

Old: torch.int32
New: torch.int64


## Random Numbers in Tensors
```python
# Returns random integers from low(inclusive) to high(exclusive)
torch.randint(low,high,size) 

# Returns samples from a standard normal distribution
torch.randn(size)

# Returns samples from a uniform distribution over [0, 1)
torch.rand(size)

In [19]:
x = torch.randint(0, 4, (2, 3))
x

tensor([[0, 0, 2],
        [0, 0, 0]])

In [20]:
x = torch.randn(3,3)
x

tensor([[ 1.2136,  1.2405, -0.4074],
        [-0.8377, -0.3012, -0.7346],
        [ 0.6592,  0.4498,  1.5651]])

In [21]:
x = torch.rand(3,3)
x

tensor([[0.3812, 0.5708, 0.7261],
        [0.3066, 0.9985, 0.1302],
        [0.7964, 0.2526, 0.0702]])

## Random Number Tensors Based on Input Size
The commands below returns the random tensor based on the input size:
```python
torch.randint_like(input,low,high)
torch.randn_like(input)
torch.rand_like(input)
```

**Note**: The same syntax can be used for zeros and ones:
```python
tensor.zeros_like(size)
tensor.ones_like(size)
```

In [22]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [23]:
# Notice the elements follow the input datatype
x1 = torch.randint_like(x,0,4)
x1

tensor([[0., 0.],
        [0., 2.]])

In [24]:
x2 = torch.ones_like(x)
x2

tensor([[1., 1.],
        [1., 1.]])

## Set the Random Seed
```python
# For getting reproducable results
torch.manual_seed(int)
```

In [25]:
torch.manual_seed(10)
x = torch.rand(3, 3)
x

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])

In [26]:
# The result should be the same as the former block
torch.manual_seed(10)
x = torch.rand(3, 3)
x

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])

## Tensor Attributes
Each torch.Tensor has a `torch.dtype`, `torch.device`, and `torch.layout`.
https://pytorch.org/docs/stable/tensor_attributes.html

In [27]:
x

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])

In [28]:
x.shape # Equivalent to x.size()

torch.Size([3, 3])

In [29]:
x.dtype

torch.float32

**Note:** 

PyTorch allows the utilization of multiple computing devices, including the use of both **CPUs** and one or more **GPUs**. It is important to understand that for any operations to occur between tensors, these **tensors must be located on the same device**.

https://pytorch.org/docs/stable/tensor_attributes.html#torch-device

In [30]:
x.device

device(type='cpu')

---

# Tensor Operations
- Indexing and slicing
- Reshape(views)
- Arithmetic and basic operations
- Dot products
- Matrix multiplication
- Advanced operatoins

### Indexing and Slicing
Check out the link for more intuitive illustration:

http://www.scipy-lectures.org/_images/numpy_indexing.png

In [31]:
x = torch.arange(4).reshape(2,2)
x

tensor([[0, 1],
        [2, 3]])

In [32]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3])

In [33]:
# Grabbing the right hand column as a (2,1) slice
x[:,1:]

tensor([[1],
        [3]])

### Reshape
The commands below could be used:
```python
x.reshape(size)
x.view(size)
```
Check the link for more explanation about `view` and `reshape`:

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [34]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [35]:
x.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [36]:
# The original Tensor remains unchanged
x

tensor([0, 1, 2, 3, 4, 5])

In [37]:
# "view" and "reshape" share the same memory with the original tensor
z = x.view(2,3)
x[0]=234
print(z)

tensor([[234,   1,   2],
        [  3,   4,   5]])


In [38]:
z = x.reshape(2,3)
x[0]=230
print(z)

tensor([[230,   1,   2],
        [  3,   4,   5]])


In [39]:
# Infer the correct size by passing -1
x.view(2,-1)

tensor([[230,   1,   2],
        [  3,   4,   5]])

In [40]:
# Adopt with another input size
x.view_as(z)

tensor([[230,   1,   2],
        [  3,   4,   5]])

In [41]:
z.shape

torch.Size([2, 3])

## Tensor Arithmetic
Adding tensors could be done in different ways:

In [42]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
a + b

tensor([5., 7., 9.])

In [43]:
# As an argument to a torch operation
torch.add(a, b)

tensor([5., 7., 9.])

In [44]:
torch.add(a, b)

tensor([5., 7., 9.])

In [45]:
# Specify the output tensor
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
result

tensor([5., 7., 9.])

**Note:**

Any operation that changes a tensor in-place, prefixed with a `_`(underscore).

In [46]:
# Chaing in place 
a.add_(b) # Equivalent to a = torch.add(a,b)

tensor([5., 7., 9.])

### Basic Tensor Operations in PyTorch

| Operation | Function     | Description                       |
|-----------|--------------|-----------------------------------|
| a + b   | `a.add(b)`   | Element-wise addition             |
| a - b   | `a.sub(b)`   | Element-wise subtraction          |
| a * b   | `a.mul(b)`   | Element-wise multiplication       |
| a / b   | `a.div(b)`   | Element-wise division             |
| a %  b   | `a.fmod(b)`  | Modulo (remainder after division) |
| a ** b  | `a.pow(b)`   | Element-wise exponentiation       |


### Monomial Operations in PyTorch

| Operation              | Function                 | Description           |
|------------------------|--------------------------|-----------------------|
| \|a\|                  | `torch.abs(a)`           | Absolute value        |
| 1/a                  | `torch.reciprocal(a)`    | Reciprocal            |
| $\sqrt{a}$            | `torch.sqrt(a)`          | Square root           |
| log(a)               | `torch.log(a)`           | Natural log           |
| $e^a$                  | `torch.exp(a)`           | Exponential           |
| 12.34  ==>  12.      | `torch.trunc(a)`         | Truncated integer     |
| 12.34  ==>  0.34     | `torch.frac(a)`          | Fractional component  |


### Trigonometry in PyTorch

| Operation  | Function          | Description         |
|------------|-------------------|---------------------|
| sin(a)   | `torch.sin(a)`    | Sine                |
| cos(a)   | `torch.cos(a)`    | Cosine              |
| tan(a)   | `torch.tan(a)`    | Tangent             |
| arcsin(a)| `torch.asin(a)`   | Arc sine            |
| arccos(a)| `torch.acos(a)`   | Arc cosine          |
| arctan(a)| `torch.atan(a)`   | Arc tangent         |
| sinh(a)  | `torch.sinh(a)`   | Hyperbolic sine     |
| cosh(a)  | `torch.cosh(a)`   | Hyperbolic cosine   |
| tanh(a)  | `torch.tanh(a)`   | Hyperbolic tangent  |


### Summary Statistics in PyTorch

| Operation       | Function          | Description      |
|-----------------|-------------------|------------------|
| $\sum a$        | `torch.sum(a)`    | Sum              |
| $\bar{a}$       | `torch.mean(a)`   | Mean             |
| a_max         | `torch.max(a)`    | Maximum          |
| a_min         | `torch.min(a)`    | Minimum          |
| 

**Note:**

`torch.max(a, b)` returns a tensor of size `a` containing the element-wise max between `a` and `b`.


In PyTorch, arithmetic operations generally require floats. For integer tensors, some operations behave differently. for example, `torch.div(a, b)` does floor division for integers and regular division for floats.

In [47]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
torch.add(a,b)

tensor([5., 7., 9.])

## Dot Products
The commands below can be used to implement dot product:
```python
torch.dot(a,b)
a.dot(b)
b.dot(a)
```

In [48]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
a.mul(b)

tensor([ 4., 10., 18.])

In [49]:
a.dot(b)

tensor(32.)

**Note:**

`torch.dot()` is solely for computing dot products of 1D arrays, while `numpy.dot()` can perform dot products with 1D arrays and matrix multiplications with 2D arrays.

Matrix multiplication can be computed using:
```python
torch.mm(a,b)
a.mm(b)
a @ b
```

In [50]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)
print('a size: ',a.shape)
print('b size: ',b.shape)
print('axb size: ',torch.mm(a,b).shape)

a size:  torch.Size([2, 3])
b size:  torch.Size([3, 2])
axb size:  torch.Size([2, 2])


In [51]:
torch.mm(a,b)

tensor([[56., 62.],
        [80., 89.]])

## Matrix Multiplication with Broadcasting
It can be computed by the commands below:
```python
torch.matmul(a,b)
a.matmul(a,b)
a @ b
```

In [54]:
t1 = torch.rand(2, 3, 4)
t2 = torch.rand(4, 5)

torch.matmul(t1, t2).size()

torch.Size([2, 3, 5])

**Note:** The command, `torch.mm()` raise a **RuntimeError**:

In [55]:
torch.mm(t1, t2).shape

RuntimeError: self must be a matrix

## Advanced Operations

### L2 or Euclidian Norm
```python
torch.norm()
```
For a vector, it returns the **Euclidian Norm** , and for a matrix, returns teh **Frobenius Norrm**:
https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm

**Note:**  Input dtype should be either **floating point or complex**.

In [58]:
x = torch.tensor([1., 2., 3.])
x.norm()

tensor(3.7417)

### Number of Elements
The command below, returns the number of elements in a tensor:
```python
torch.numel()
```
For such a case like calculating MSE, it could be useful:
```python
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
```

In [59]:
x = torch.rand(2, 3)
x.numel()

6

In [60]:
# "len()" returns the first element of the x.shape
len(x)

2