# Introduction
---

In [1]:
import torch

# Tensors

In [10]:
# 1D tensor
a = torch.tensor([2, 1, 1])
a

tensor([2, 1, 1])

In [12]:
# 2D tensor
b = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
print(a.shape, a.size())

torch.Size([3]) torch.Size([3])


In [15]:
print(b.shape, b.shape[0])

torch.Size([3, 3]) 3


In [16]:
c = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = torch.DoubleTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# c = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
# d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.double)

In [17]:
print(c, c.dtype)
print(d, d.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64) torch.float64


In [18]:
print(c.mean(), c.std())

tensor(5.) tensor(2.7386)


In [22]:
# Reshape
print(b.reshape(1, 9),'\n', b.reshape(9), '\n', b.reshape(-1, 3))
# b.view() do the same thing.

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) 
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [24]:
# Generate random numbers between 0 and 1
r = torch.rand(4, 4)
r

tensor([[0.7693, 0.9998, 0.8570, 0.5392],
        [0.4387, 0.0956, 0.5906, 0.5543],
        [0.7542, 0.8011, 0.3169, 0.6890],
        [0.9224, 0.7381, 0.6522, 0.4128]])

In [25]:
# Generate random numbers from a standard normal distribution
r = torch.randn(4, 4)
print(r, r.dtype)

tensor([[ 1.7833, -1.7511,  0.1844, -0.2660],
        [-0.0194, -1.3660, -0.7160,  0.3823],
        [-0.7011,  0.4793,  0.1889, -0.4169],
        [ 1.3475,  0.4607, -0.0576, -0.6788]]) torch.float32


In [27]:
# Generate random integer numbers between the limits(exclusive max)
r = torch.randint(6, 10, (4, 4))
print(r, r.dtype)

tensor([[7, 6, 6, 7],
        [6, 6, 7, 6],
        [9, 6, 6, 7],
        [6, 6, 7, 8]]) torch.int64


In [32]:
# 3D tensor (channel, row, column)
d = torch.randn(3, 2, 2)
d

tensor([[[ 0.3419,  0.3739],
         [ 0.2906, -0.3094]],

        [[-0.1416,  0.1641],
         [ 0.4433, -0.6833]],

        [[-0.1280,  0.6222],
         [ 0.8477,  0.8139]]])

In [34]:
# Get the number of elements
torch.numel(d)

12

In [36]:
# Zeroes and ones(with dtype specification)
z = torch.zeros(3, 3, dtype=torch.long)
print(z, z.dtype)
o = torch.ones(3, 3)
print(o, o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) torch.int64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [38]:
# Like
z_like = torch.randn_like(z, dtype=torch.double)
z_like

tensor([[ 0.1935, -0.1559,  0.4119],
        [ 1.1482, -0.9078, -0.7300],
        [ 0.5066, -1.4494,  0.5402]], dtype=torch.float64)

In [44]:
# Add (two tensors should have the same(supportive) size and data type)
arr_add = torch.add(z, z_like)
arr_add

tensor([[ 0.1935, -0.1559,  0.4119],
        [ 1.1482, -0.9078, -0.7300],
        [ 0.5066, -1.4494,  0.5402]], dtype=torch.float64)

In [43]:
# In-place add
z_like.add_(z)
z_like

tensor([[ 0.1935, -0.1559,  0.4119],
        [ 1.1482, -0.9078, -0.7300],
        [ 0.5066, -1.4494,  0.5402]], dtype=torch.float64)

In [48]:
# Slicing(same as python slicing)
z_like[:,:2]

tensor([[ 0.1935, -0.1559],
        [ 1.1482, -0.9078],
        [ 0.5066, -1.4494]], dtype=torch.float64)

In [53]:
# Extract element
num = z_like[1, 2]
print(num, num.item())

tensor(-0.7300, dtype=torch.float64) -0.7300303752455789


# Numpy array, Torch tensor 

In [54]:
import numpy as np

In [59]:
# Convert torch-tensor to numpy array
a = torch.ones(2, 2)
b = a.numpy()
b

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [58]:
# Pay attention to ALIASING
a.add_(1)
print(a,'\n', b)

tensor([[4., 4.],
        [4., 4.]]) 
 [[4. 4.]
 [4. 4.]]


In [61]:
# Convert numpy array to torch tensor
a = torch.from_numpy(b)
a

tensor([[1., 1.],
        [1., 1.]])

In [64]:
# Move tensor to GPU(get error because the lack of gpu on the system)
a = a.cuda()
a

AssertionError: Torch not compiled with CUDA enabled

In [66]:
# Easy switch between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    a = a.cuda()

False


In [70]:
# Concatenation along rows(dimension = 0, default), should have same column size
arr1 = torch.randn(2, 3)
arr2 = torch.randn(4, 3)
concat_ = torch.cat([arr1, arr2])
print(concat_, concat_.shape)

tensor([[-0.9633,  0.3408, -0.4542],
        [ 0.4209,  1.0426,  1.0250],
        [-0.3061,  1.7100,  0.6981],
        [ 0.7492, -0.1376,  0.4646],
        [ 2.0434,  1.5619, -0.1992],
        [-1.0967,  0.3861,  0.2547]]) torch.Size([6, 3])


In [71]:
# Concatenation along columns(dimension = 1), should have same row size
arr1 = torch.randn(2, 1)
arr2 = torch.randn(2, 3)
concat_ = torch.cat([arr1, arr2], dim=1)
print(concat_, concat_.shape)

tensor([[-0.0536, -0.1542,  1.5899,  0.2928],
        [-0.4388,  0.9657, -0.6378,  0.0411]]) torch.Size([2, 4])


In [5]:
# Add dimensios 
arr = torch.tensor([1, 2, 3, 4])
ext_arr = torch.unsqueeze(arr, dim=0)
ext2_arr = torch.unsqueeze(arr, dim=1)
print(arr.shape, ext_arr.shape, ext2_arr.shape)

torch.Size([4]) torch.Size([1, 4]) torch.Size([4, 1])


In [7]:
rand_arr = torch.rand(2, 3, 4)
ext_rand_arr = torch.unsqueeze(rand_arr, 1)
print(rand_arr.shape, ext_rand_arr.shape)

torch.Size([2, 3, 4]) torch.Size([2, 1, 3, 4])
